auto: true
destination: ../tecmogeek-production

markdown: rdiscount
rdiscount:
 extensions: [smart]

permalink: "pretty"
exclude:
 - README.md

qb-text: All QB have Running Speed 25, Rushing Power 69, and Hitting Power 13. Accuracy of Passing has no effect on performance.
rb-wr-te-text: All RB, WR and TE have Rushing Power 69.
kr-text: Due to a programming glitch, all KR have the same Maximum Speed as their team&rsquo;s RT.
pr-text: Due to a programming glitch, all PR have the same Maximum Speed as their team&rsquo;s SS and Ball Control 44.
ol-text: All OL have Running Speed 25 and Rushing Power 69.
defense-text: Quickness has no effect on performance for any defensive player.
k-text: All K have Running Speed 56, Rushing Power 81, Maximum Speed 81, and Hitting Power 31.
p-text: All P have Running Speed 25, Rushing Power 56, Maximum Speed 44, and Hitting Power 31.

